[programs.localnet]
trainer = "BDQCsoSkfhrNjzjQChgtHExVgrjNvwYKhkRibDLHDtY3"

[programs.devnet]
trainer = "BDQCsoSkfhrNjzjQChgtHExVgrjNvwYKhkRibDLHDtY3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/trainer"]

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000"
