[package]
name = "trainer"
version = "0.1.0"
description = "Cooperaty's practice trading program"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "trainer"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.18.0"
